[package]
name = "notectl"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.22", features = ["derive", "env"]}
redis = { version = "0.27.6", features = ["tokio-rustls-comp", "cluster", "json", "r2d2"] }
sea-orm = { version = "1.1.2", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
serde = { version = "1.0.215", features = ["derive", "serde_derive"]}
serde_yml = "0.0.12"
tokio = { version = "1.42.0", features = ["full"] }
