services:
  web:
    image: ${CONTAINER_IMAGE}:${SOFTWARE_VERSION}
    ports:
      - "3030:3030"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal_network
      - external_network
    volumes:
      - ./.config/:/misskey/.config
      - ./files:/misskey/files

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    networks:
      - internal_network
      - external_network
    environment:
      POSTGRES_DB: misskey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./meilisearch:/data.ms
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=5acc97a208a444a84413f73e5bf40db153860082
      - MEILI_ENV=development

networks:
  internal_network:
    internal: true
  external_network:

volumes:
  db:
  redis:
  meilisearch: