//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use super::sea_orm_active_enums::NoteDraftVisibilityEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "note_draft")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: String,
  #[sea_orm(column_name = "replyId")]
  pub reply_id: Option<String>,
  #[sea_orm(column_name = "renoteId")]
  pub renote_id: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub text: Option<String>,
  pub cw: Option<String>,
  #[sea_orm(column_name = "userId")]
  pub user_id: String,
  #[sea_orm(column_name = "localOnly")]
  pub local_only: bool,
  #[sea_orm(column_name = "reactionAcceptance")]
  pub reaction_acceptance: Option<String>,
  pub visibility: NoteDraftVisibilityEnum,
  #[sea_orm(column_name = "fileIds")]
  pub file_ids: Vec<String>,
  #[sea_orm(column_name = "visibleUserIds")]
  pub visible_user_ids: Vec<String>,
  pub hashtag: Option<String>,
  #[sea_orm(column_name = "channelId")]
  pub channel_id: Option<String>,
  #[sea_orm(column_name = "hasPoll")]
  pub has_poll: bool,
  #[sea_orm(column_name = "pollChoices")]
  pub poll_choices: Vec<String>,
  #[sea_orm(column_name = "pollMultiple")]
  pub poll_multiple: bool,
  #[sea_orm(column_name = "pollExpiresAt")]
  pub poll_expires_at: Option<DateTimeWithTimeZone>,
  #[sea_orm(column_name = "pollExpiredAfter")]
  pub poll_expired_after: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::UserId",
    to = "super::user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  User,
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::User.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
