name: On Release Created (Publish binary)

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - target: x86_64-unknown-linux-gnu
                      platform: linux/amd64
                      arch: x86_64
                    - target: x86_64-unknown-linux-musl
                      platform: linux/amd64
                      arch: x86_64
                    - target: aarch64-unknown-linux-gnu
                      platform: linux/arm64
                      arch: aarch64
                    - target: aarch64-unknown-linux-musl
                      platform: linux/arm64
                      arch: aarch64
                    - target: x86_64-unknown-freebsd
                      platform: freebsd/amd64
                      arch: x86_64
                    - target: aarch64-apple-darwin
                      platform: darwin/arm64
                      arch: aarch64
                    - target: x86_64-apple-darwin
                      platform: darwin/amd64
                      arch: x86_64
                    - target: riscv64gc-unknown-linux-gnu
                      platform: linux/riscv64
                      arch: riscv64
                    - target: riscv64gc-unknown-linux-musl
                      platform: linux/riscv64
                      arch: riscv64
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          
          - name: Set up Rust
            run: |
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              export PATH="$HOME/.cargo/bin:$PATH"
              source $HOME/.cargo/env
              rustup default stable
              rustup update
              rustup component add clippy
              rustup target add ${{ matrix.target }}
              cargo install clippy-sarif sarif-fmt cross

          - name: Build binary
            run: cross build --release --target ${{ matrix.target }}

          - name: Package binary
            run: |
              mkdir -p artifacts
              cd target/release
              tar -czf ../../artifacts/notectl-${{ matrix.target }}-${{ github.event.release.tag_name }}-tar.gz notectl

          - name: Upload binary
            uses: softprops/action-gh-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
            with:
              files: |
                artifacts/notectl-${{ matrix.target }}-${{ github.event.release.tag_name }}-tar.gz
