name: On Release Created (Publish binary)

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ${{ matrix.runner }}
        strategy:
            matrix:
                include:
                    - runner: ubuntu-latest
                      platform: linux/amd64
                      arch: amd64
                    - runner: ubuntu-24.04-arm
                      platform: linux/arm64
                      arch: arm64
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          
          - name: Set up Rust
            run: |
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              export PATH="$HOME/.cargo/bin:$PATH"
              source $HOME/.cargo/env
              rustup default stable
              rustup update
              rustup component add clippy
              cargo install clippy-sarif sarif-fmt

          - name: Build binary
            run: cargo build --release

          - name: Package binary
            run: |
              mkdir -p artifacts
              cd target/release
              tar -czf ../../notectl-linux-${{ matrix.arch }}.tar.gz notectl

          - name: Upload binary
            uses: actions/upload-artifact@v4
            with:
              name: notectl-${{ matrix.arch }}.tar.gz
              path: artifacts/notectl-linux-${{ matrix.arch }}.tar.gz
